In [5]:
import numpy as np
import time
from scipy import linalg
import qiskit
import itertools

In [6]:
# Initialize a random number generator
rng = np.random.default_rng()

In [95]:
def grid_adj_mat(rows,columns):
    # Returns the adjacency matrix of a grid with rows number of rows and columns number of columns
    
    N = rows*columns
    
    graph = np.zeros((N,N))
    for j in range(rows-1):
        for i in range(columns-1):
            graph[j*columns + i,j*columns + i + 1] = 1
            graph[j*columns + i + 1,j*columns + i] = 1
            graph[j*columns + i, (j + 1)*columns + i] = 1
            graph[(j + 1)*columns + i, j*columns + i] = 1
    
    for j in range(rows-1):
        graph[j*columns + columns - 1, (j + 1)*columns + columns - 1] = 1
        graph[(j + 1)*columns + columns - 1, j*columns + columns - 1] = 1
        
    for i in range(columns-1):
        graph[(rows - 1)*columns + i,(rows - 1)*columns + i + 1] = 1
        graph[(rows - 1)*columns + i + 1,(rows - 1)*columns + i] = 1
           
    return graph

In [ ]:
def level_up(graph):
    # Run at beginning of each level
    
    prey_location = rng.integers(graph.shape[0]) # randomly choose a new prey_location

In [50]:
def distances(graph):
    # Returns array with each entry being the shortest distance between
    # two vertices.
    # The input is the adjacency matrix of the graph
    # Uses the Floyd-Warshall algorithm
    N = graph.shape[0]
    dist = np.full((N,N),np.inf)
    print(dist)
    dist[graph==1] = 1
    print(dist)
    dist[range(N),range(N)] = 0
    print(dist)
    for k in range(N):
        for i in range(N):
            for j in range(N):
                if dist[i,j] > dist[i,k] + dist[k,j]:
                    dist[i,j] = dist[i,k] + dist[k,j]
    return dist

In [85]:
def probeable_vertices(graph, snake_body):
    # Returns a list of vertices that the user is allowed to probe.
    # Where snake_body is a list of vertices, the first being the snake's 
    # tail and the last being the snake's head.
    # And where graph is the adjacency matrix of the graph
    
    assert len(snake_body) > 1, 'The snake\'s body must be two or more vertices.'
    
    vect = graph[snake_body[-1]] # 1 for vertices adjacent to head, 0 otherwise
    vect[snake_body[-2]] = 0 # Remove the space just behind the snake's head
    
    # Return indices of vertices that are adjacent to the head, but not just
    # behind the head.
    return np.where(vect)[0]

In [86]:
def query(graph, dist, snake_body, probe_vector, prey_location):
    # Given a probe state and the prey's location, this function returns
    # the measured distance resulting from the probe as well as the new
    # probe state that remains after measurement.
    
    probed_vertices = probeable_vertices(graph,snake_body) # vertices to be probed
    
    distances = dist[probe_vertices,prey_location]
    # distances from probed vertices to the prey
    
    probabilites = np.abs(probe_vector)**2 #probs. of the different outcomes
    probabilities = probabilities/np.sum(probabilities) # enforce summing up to 1
    
    measured_distance = rng.choice(distances,p=probabilities)
    
    # Get resulting state after measurement
    new_probe_vector = np.copy(probe_vector)
    new_probe_vector[distances!=measured_distance] = 0
    
    # Normalize
    norm = np.sum(np.abs(new_probe_vector)**2)**0.5
    new_probe_vector = new_probe_vector/norm
    new_norm = np.sum(np.abs(new_probe_vector)**2)
    assert new_norm==1, f'Norm is {new_norm}, but it should be 1.'
    
    return measured_distance, new_probe_vector

In [ ]:
def query_all_cases(graph, dist, snake_body, probe_vector_all_cases, measured_distance):
    
    
    probed_vertices = probeable_vertices(graph,snake_body)
    
    distances = dist[prob_vertices,:]
    
    new_probe_vector_all_cases = np.copy(probe_vector_all_cases)
    new_probe_vector_all_cases[distances!=measured_distance] = 0
    
    return new_probe_vector_all_cases
    
def hint(graph, dist, snake_body, probe_vector_all_cases, prey_location):
    
    good_moves_vectors = linalg.sqrtm(probe_vector_all_cases.conj().T@probe_vector_all_cases)
    good_moves_vector = good_moves_vectors[prey_location]
    
    probabilities = np.abs(good_moves_vector)**2
    good_move = rng.choice(range(len(good_moves_vector)),p=probabilities)
    
    return good_move

In [ ]:
def probe_measurement(graph, snake_body, probe_vector):
    # Returns the index of a vertex that results from measuring the 
    # given probe state.
    
    probed_vertices = probeable_vertices(graph,snake_body) # vertices that were probed
    
    probabilities = np.abs(probe_vector)**2 # probabilities of different outcomes
    
    # Randomly choose a vertex according to Born rule probabilities.
    measured_vertex = rng.choice(probed_vertices,p=probabilities)
    
    return measured_vertex

In [88]:
def probe_unitary(unitary_mat, probe_vector):
    # Simply multiplies the probe state by the given unitary matrix
    
    n = unitary_mat.shape(1)
    assert n==len(probe_vector), 'Probe vector dimension doesn\'t match.'
    assert n==unitary_mat.shape(0), 'Given matrix not square'
    assert unitary_mat.conj().T@unitary_mat==np.eye(n), 'Given matrix not unitary'
    
    return unitary_mat@probe_vector
    

In [ ]:
def path_to_vertex(graph, snake_body, vertex):
    # This finds and outputs a path to the chosen vertex, taking into
    # account the snake's current position.
    # If possible, it returns a path such that the snake doesn't collide
    # with itself.
    # If no path without collision is possible, status returns False,
    # and the returned path is truncated to end at the collision point.
    
    
    # [Not necessary]
    
    
    return path, status

In [ ]:
def hint()

In [ ]:
def strike_button(prey_location, guess):
    if guess==prey_location:
        
        # [prey location is revealed to player]
        prey_revealed = True
        
        # [player is asked to move snake to prey location]
        
        
        
    else:
        life_count -= 1 #increment the number of lives downward.
        if life_count <1:
            
            # [UI tells you you're dead. Game over]
            
        else:
            
            # [Take player back to "beginning of turn state" so they can continue playing]

In [ ]:
def on_button_up(rows, columns, prey_revealed, prey_location): # and similar functions for down, left, right
    
    head = snake_body[-1]
    new_head = head - columns # index of square one above the head. Replace for other directions.
    
    # Detect collision with edge
    if new_head not in range(rows*columns):
        # Do nothing. I.e. ignore when player tells snake to move off grid.
        return
    
    # Detect collision with self
    if new_head in snake_body[1:]:
        
        # [UI tells you you're dead. Game over]
        
        return
    
    # Move snake
    snake_body.append(new_head)
    # Grow snake only when the prey location is revealed and prey is reached
    if not (prey_revealed and new_head==prey_location):
        snake_body.pop(0)
        
    return

In [9]:
testmat = np.arange(12).reshape((3,4))
print(testmat)
testmat[[1,2,0],2]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6, 10,  2])